name: Trigger auto deployment for container-app-5igfahzybkbtc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-5igfahzybkbtc-AutoDeployTrigger-58743b92-2e1e-4bde-9209-2bdaf3807d69.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5IGFAHZYBKBTC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5IGFAHZYBKBTC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5IGFAHZYBKBTC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP5IGFAHZYBKBTC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP5IGFAHZYBKBTC_REGISTRY_PASSWORD }}
          containerAppName: container-app-5igfahzybkbtc
          resourceGroup: todonodejspgsqlgoogleautha92e8894
          imageToBuild: default/container-app-5igfahzybkbtc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


